version: '3.7'

services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2020-03-06T22-23-56Z
    ports:
      - "9000:9000"
    volumes:
      - "./data:/data"
    networks: 
      - backend
    environment:
      MINIO_ACCESS_KEY: minio # You are expected to change this
      MINIO_SECRET_KEY: minio123 # You are expected to change this
    command: server /data/minio 
  worker:
    container_name: worker
    depends_on:
      - minio
    networks:
    - backend
    build: "."

networks:
  backend:
    driver: "bridge"
